//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVAIntegrationModeler.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    // ✅ MUSÍ BÝT: "AVAIntegrationModeler.Web.Resources.SharedResources"
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(
                        "AVAIntegrationModeler.Web.Resources.SharedResources",  // ← TOTO MUSÍ SEDĚT!
                        typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string DataModels_Code {
            get {
                return ResourceManager.GetString("DataModels.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard: {0}.
        /// </summary>
        public static string DataModels_CopiedToClipboard {
            get {
                return ResourceManager.GetString("DataModels.CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string DataModels_CopyToClipboard {
            get {
                return ResourceManager.GetString("DataModels.CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DataModels_Description {
            get {
                return ResourceManager.GetString("DataModels.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string DataModels_Identifier {
            get {
                return ResourceManager.GetString("DataModels.Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Aggregate Root.
        /// </summary>
        public static string DataModels_IsAggregateRoot {
            get {
                return ResourceManager.GetString("DataModels.IsAggregateRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataModels_Name {
            get {
                return ResourceManager.GetString("DataModels.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DataModels_Notes {
            get {
                return ResourceManager.GetString("DataModels.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string DataModels_Search {
            get {
                return ResourceManager.GetString("DataModels.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Models.
        /// </summary>
        public static string DataModels_Title {
            get {
                return ResourceManager.GetString("DataModels.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVA Place.
        /// </summary>
        public static string Datasource_AVAPlace {
            get {
                return ResourceManager.GetString("Datasource.AVAPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Development.
        /// </summary>
        public static string Datasource_LocalDevelopment {
            get {
                return ResourceManager.GetString("Datasource.LocalDevelopment", resourceCulture);
            }
        }
    }
}
