// <auto-generated />
using System;
using AVAIntegrationModeler.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVAIntegrationModeler.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250915235452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("AVAIntegrationModeler.Core.ContributorAggregate.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Contributors");
                });

            modelBuilder.Entity("AVAIntegrationModeler.Core.ScenarioAggregate.Scenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InputFeature")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutputFeature")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("AVAIntegrationModeler.Core.ContributorAggregate.Contributor", b =>
                {
                    b.OwnsOne("AVAIntegrationModeler.Core.ContributorAggregate.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("ContributorId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Extension")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContributorId");

                            b1.ToTable("Contributors");

                            b1.WithOwner()
                                .HasForeignKey("ContributorId");
                        });

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("AVAIntegrationModeler.Core.ScenarioAggregate.Scenario", b =>
                {
                    b.OwnsOne("AVAIntegrationModeler.Core.ValueObjects.LocalizedValue", "Description", b1 =>
                        {
                            b1.Property<Guid>("ScenarioId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CzechValue")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EnglishValue")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ScenarioId");

                            b1.ToTable("Scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioId");
                        });

                    b.OwnsOne("AVAIntegrationModeler.Core.ValueObjects.LocalizedValue", "Name", b1 =>
                        {
                            b1.Property<Guid>("ScenarioId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CzechValue")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EnglishValue")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ScenarioId");

                            b1.ToTable("Scenarios");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
