//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVAIntegrationModeler.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVAIntegrationModeler.Localization.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models records.
        /// </summary>
        public static string DataModelRecords {
            get {
                return ResourceManager.GetString("DataModelRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string DataModels_Code {
            get {
                return ResourceManager.GetString("DataModels.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard: {0}.
        /// </summary>
        public static string DataModels_CopiedToClipboard {
            get {
                return ResourceManager.GetString("DataModels.CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string DataModels_CopyToClipboard {
            get {
                return ResourceManager.GetString("DataModels.CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DataModels_Description {
            get {
                return ResourceManager.GetString("DataModels.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string DataModels_Identifier {
            get {
                return ResourceManager.GetString("DataModels.Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Aggregate Root.
        /// </summary>
        public static string DataModels_IsAggregateRoot {
            get {
                return ResourceManager.GetString("DataModels.IsAggregateRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataModels_Name {
            get {
                return ResourceManager.GetString("DataModels.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string DataModels_Notes {
            get {
                return ResourceManager.GetString("DataModels.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string DataModels_Search {
            get {
                return ResourceManager.GetString("DataModels.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Models.
        /// </summary>
        public static string DataModels_Title {
            get {
                return ResourceManager.GetString("DataModels.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVA Place.
        /// </summary>
        public static string Datasource_AVAPlace {
            get {
                return ResourceManager.GetString("Datasource.AVAPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Development.
        /// </summary>
        public static string Datasource_LocalDevelopment {
            get {
                return ResourceManager.GetString("Datasource.LocalDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        public static string Scenarios {
            get {
                return ResourceManager.GetString("Scenarios", resourceCulture);
            }
        }

        public static string Common_Code { get { return ResourceManager.GetString("Common.Code", resourceCulture); } }
        public static string Common_Name { get { return ResourceManager.GetString("Common.Name", resourceCulture); } }
        public static string Common_Description { get { return ResourceManager.GetString("Common.Description", resourceCulture); } }
        public static string Common_Actions { get { return ResourceManager.GetString("Common.Actions", resourceCulture); } }
        public static string Common_Edit { get { return ResourceManager.GetString("Common.Edit", resourceCulture); } }
        public static string Common_Delete { get { return ResourceManager.GetString("Common.Delete", resourceCulture); } }
        public static string Common_Save { get { return ResourceManager.GetString("Common.Save", resourceCulture); } }
        public static string Common_Back { get { return ResourceManager.GetString("Common.Back", resourceCulture); } }
        public static string Common_BackToList { get { return ResourceManager.GetString("Common.BackToList", resourceCulture); } }
        public static string Common_Copy { get { return ResourceManager.GetString("Common.Copy", resourceCulture); } }
        public static string Common_CopyIdToClipboard { get { return ResourceManager.GetString("Common.CopyIdToClipboard", resourceCulture); } }
        public static string Common_IdCopied { get { return ResourceManager.GetString("Common.IdCopied", resourceCulture); } }
        public static string Common_ShowMap { get { return ResourceManager.GetString("Common.ShowMap", resourceCulture); } }
        public static string Common_Loading { get { return ResourceManager.GetString("Common.Loading", resourceCulture); } }
        public static string Common_LoadingData { get { return ResourceManager.GetString("Common.LoadingData", resourceCulture); } }
        public static string Common_Refresh { get { return ResourceManager.GetString("Common.Refresh", resourceCulture); } }
        public static string Common_Add { get { return ResourceManager.GetString("Common.Add", resourceCulture); } }
        public static string Common_Remove { get { return ResourceManager.GetString("Common.Remove", resourceCulture); } }
        public static string Common_Yes { get { return ResourceManager.GetString("Common.Yes", resourceCulture); } }
        public static string Common_No { get { return ResourceManager.GetString("Common.No", resourceCulture); } }
        public static string Common_Czech { get { return ResourceManager.GetString("Common.Czech", resourceCulture); } }
        public static string Common_English { get { return ResourceManager.GetString("Common.English", resourceCulture); } }
        public static string Common_NameCzech { get { return ResourceManager.GetString("Common.NameCzech", resourceCulture); } }
        public static string Common_NameEnglish { get { return ResourceManager.GetString("Common.NameEnglish", resourceCulture); } }
        public static string Common_DescriptionCzech { get { return ResourceManager.GetString("Common.DescriptionCzech", resourceCulture); } }
        public static string Common_DescriptionEnglish { get { return ResourceManager.GetString("Common.DescriptionEnglish", resourceCulture); } }
        public static string Common_Database { get { return ResourceManager.GetString("Common.Database", resourceCulture); } }
        public static string Common_Area { get { return ResourceManager.GetString("Common.Area", resourceCulture); } }
        public static string Common_TryAgain { get { return ResourceManager.GetString("Common.TryAgain", resourceCulture); } }
        public static string Common_Status { get { return ResourceManager.GetString("Common.Status", resourceCulture); } }
        public static string Common_UnexpectedError { get { return ResourceManager.GetString("Common.UnexpectedError", resourceCulture); } }

        public static string NavMenu_Areas { get { return ResourceManager.GetString("NavMenu.Areas", resourceCulture); } }
        public static string NavMenu_AreaMap { get { return ResourceManager.GetString("NavMenu.AreaMap", resourceCulture); } }
        public static string NavMenu_Deployments { get { return ResourceManager.GetString("NavMenu.Deployments", resourceCulture); } }
        public static string NavMenu_AIAssistant { get { return ResourceManager.GetString("NavMenu.AIAssistant", resourceCulture); } }
        public static string NavMenu_Rules { get { return ResourceManager.GetString("NavMenu.Rules", resourceCulture); } }

        public static string Areas_Title { get { return ResourceManager.GetString("Areas.Title", resourceCulture); } }
        public static string Areas_AddNew { get { return ResourceManager.GetString("Areas.AddNew", resourceCulture); } }
        public static string Areas_DataModelsColumn { get { return ResourceManager.GetString("Areas.DataModelsColumn", resourceCulture); } }
        public static string Areas_NoDataModels { get { return ResourceManager.GetString("Areas.NoDataModels", resourceCulture); } }
        public static string Areas_DataModelsCount { get { return ResourceManager.GetString("Areas.DataModelsCount", resourceCulture); } }
        public static string Areas_FieldsCount { get { return ResourceManager.GetString("Areas.FieldsCount", resourceCulture); } }
        public static string Areas_NewTitle { get { return ResourceManager.GetString("Areas.NewTitle", resourceCulture); } }
        public static string Areas_EditTitle { get { return ResourceManager.GetString("Areas.EditTitle", resourceCulture); } }
        public static string Areas_CodePlaceholder { get { return ResourceManager.GetString("Areas.CodePlaceholder", resourceCulture); } }
        public static string Areas_NamePlaceholder { get { return ResourceManager.GetString("Areas.NamePlaceholder", resourceCulture); } }
        public static string Areas_DeleteConfirm { get { return ResourceManager.GetString("Areas.DeleteConfirm", resourceCulture); } }
        public static string Areas_DeletedSuccess { get { return ResourceManager.GetString("Areas.DeletedSuccess", resourceCulture); } }
        public static string Areas_DeletedError { get { return ResourceManager.GetString("Areas.DeletedError", resourceCulture); } }
        public static string Areas_SavedSuccess { get { return ResourceManager.GetString("Areas.SavedSuccess", resourceCulture); } }
        public static string Areas_CreatedSuccess { get { return ResourceManager.GetString("Areas.CreatedSuccess", resourceCulture); } }

        public static string Scenarios_Title { get { return ResourceManager.GetString("Scenarios.Title", resourceCulture); } }
        public static string Scenarios_AddNew { get { return ResourceManager.GetString("Scenarios.AddNew", resourceCulture); } }
        public static string Scenarios_InputFeature { get { return ResourceManager.GetString("Scenarios.InputFeature", resourceCulture); } }
        public static string Scenarios_OutputFeature { get { return ResourceManager.GetString("Scenarios.OutputFeature", resourceCulture); } }
        public static string Scenarios_EditTitle { get { return ResourceManager.GetString("Scenarios.EditTitle", resourceCulture); } }
        public static string Scenarios_CodePlaceholder { get { return ResourceManager.GetString("Scenarios.CodePlaceholder", resourceCulture); } }
        public static string Scenarios_LinkedFeatures { get { return ResourceManager.GetString("Scenarios.LinkedFeatures", resourceCulture); } }
        public static string Scenarios_SelectInputFeature { get { return ResourceManager.GetString("Scenarios.SelectInputFeature", resourceCulture); } }
        public static string Scenarios_SelectOutputFeature { get { return ResourceManager.GetString("Scenarios.SelectOutputFeature", resourceCulture); } }
        public static string Scenarios_SavedSuccess { get { return ResourceManager.GetString("Scenarios.SavedSuccess", resourceCulture); } }
        public static string Scenarios_Created { get { return ResourceManager.GetString("Scenarios.Created", resourceCulture); } }
        public static string Scenarios_Saved { get { return ResourceManager.GetString("Scenarios.Saved", resourceCulture); } }

        public static string DataModels_TitleDatabase { get { return ResourceManager.GetString("DataModels.TitleDatabase", resourceCulture); } }
        public static string DataModels_AddNew { get { return ResourceManager.GetString("DataModels.AddNew", resourceCulture); } }
        public static string DataModels_DeleteAll { get { return ResourceManager.GetString("DataModels.DeleteAll", resourceCulture); } }
        public static string DataModels_AggregateRootColumn { get { return ResourceManager.GetString("DataModels.AggregateRootColumn", resourceCulture); } }
        public static string DataModels_FieldsColumn { get { return ResourceManager.GetString("DataModels.FieldsColumn", resourceCulture); } }
        public static string DataModels_ModelMap { get { return ResourceManager.GetString("DataModels.ModelMap", resourceCulture); } }
        public static string DataModels_CompareWithAvaPlace { get { return ResourceManager.GetString("DataModels.CompareWithAvaPlace", resourceCulture); } }
        public static string DataModels_FieldsSection { get { return ResourceManager.GetString("DataModels.FieldsSection", resourceCulture); } }
        public static string DataModels_NewTitle { get { return ResourceManager.GetString("DataModels.NewTitle", resourceCulture); } }
        public static string DataModels_EditTitle { get { return ResourceManager.GetString("DataModels.EditTitle", resourceCulture); } }
        public static string DataModels_AreaOptional { get { return ResourceManager.GetString("DataModels.AreaOptional", resourceCulture); } }
        public static string DataModels_AggregateRootLabel { get { return ResourceManager.GetString("DataModels.AggregateRootLabel", resourceCulture); } }
        public static string DataModels_AggregateRootDetail { get { return ResourceManager.GetString("DataModels.AggregateRootDetail", resourceCulture); } }
        public static string DataModels_TitleAvaPlace { get { return ResourceManager.GetString("DataModels.TitleAvaPlace", resourceCulture); } }
        public static string DataModels_ImportAll { get { return ResourceManager.GetString("DataModels.ImportAll", resourceCulture); } }
        public static string DataModels_ImportToDatabase { get { return ResourceManager.GetString("DataModels.ImportToDatabase", resourceCulture); } }
        public static string DataModels_Documentation { get { return ResourceManager.GetString("DataModels.Documentation", resourceCulture); } }
        public static string DataModels_StatusSame { get { return ResourceManager.GetString("DataModels.StatusSame", resourceCulture); } }
        public static string DataModels_StatusDifferent { get { return ResourceManager.GetString("DataModels.StatusDifferent", resourceCulture); } }
        public static string DataModels_StatusOnlyInDatabase { get { return ResourceManager.GetString("DataModels.StatusOnlyInDatabase", resourceCulture); } }
        public static string DataModels_StatusOnlyInAvaPlace { get { return ResourceManager.GetString("DataModels.StatusOnlyInAvaPlace", resourceCulture); } }
        public static string DataModels_StatusOnlyDb { get { return ResourceManager.GetString("DataModels.StatusOnlyDb", resourceCulture); } }
        public static string DataModels_StatusOnlyAva { get { return ResourceManager.GetString("DataModels.StatusOnlyAva", resourceCulture); } }
        public static string DataModels_CompareDbVsAvaPlace { get { return ResourceManager.GetString("DataModels.CompareDbVsAvaPlace", resourceCulture); } }

        public static string DataModelChanges_Title { get { return ResourceManager.GetString("DataModelChanges.Title", resourceCulture); } }
        public static string DataModelChanges_LoadingComparison { get { return ResourceManager.GetString("DataModelChanges.LoadingComparison", resourceCulture); } }
        public static string DataModelChanges_ModelProperties { get { return ResourceManager.GetString("DataModelChanges.ModelProperties", resourceCulture); } }
        public static string DataModelChanges_AllPropertiesSame { get { return ResourceManager.GetString("DataModelChanges.AllPropertiesSame", resourceCulture); } }
        public static string DataModelChanges_PropertyColumn { get { return ResourceManager.GetString("DataModelChanges.PropertyColumn", resourceCulture); } }
        public static string DataModelChanges_ModelFields { get { return ResourceManager.GetString("DataModelChanges.ModelFields", resourceCulture); } }
        public static string DataModelChanges_NoFields { get { return ResourceManager.GetString("DataModelChanges.NoFields", resourceCulture); } }
        public static string DataModelChanges_SameFieldsHidden { get { return ResourceManager.GetString("DataModelChanges.SameFieldsHidden", resourceCulture); } }
        public static string DataModelChanges_ShowSameFields { get { return ResourceManager.GetString("DataModelChanges.ShowSameFields", resourceCulture); } }
        public static string DataModelChanges_HideSameFields { get { return ResourceManager.GetString("DataModelChanges.HideSameFields", resourceCulture); } }
        public static string DataModelChanges_TotalCount { get { return ResourceManager.GetString("DataModelChanges.TotalCount", resourceCulture); } }
        public static string DataModelChanges_DifferentCount { get { return ResourceManager.GetString("DataModelChanges.DifferentCount", resourceCulture); } }

        public static string Deployments_Title { get { return ResourceManager.GetString("Deployments.Title", resourceCulture); } }
        public static string Deployments_AddNew { get { return ResourceManager.GetString("Deployments.AddNew", resourceCulture); } }
        public static string Deployments_LastDeployment { get { return ResourceManager.GetString("Deployments.LastDeployment", resourceCulture); } }
        public static string Deployments_ExportTitle { get { return ResourceManager.GetString("Deployments.ExportTitle", resourceCulture); } }
        public static string Deployments_NewTitle { get { return ResourceManager.GetString("Deployments.NewTitle", resourceCulture); } }
        public static string Deployments_EditTitle { get { return ResourceManager.GetString("Deployments.EditTitle", resourceCulture); } }
        public static string Deployments_CodePlaceholder { get { return ResourceManager.GetString("Deployments.CodePlaceholder", resourceCulture); } }
        public static string Deployments_NamePlaceholder { get { return ResourceManager.GetString("Deployments.NamePlaceholder", resourceCulture); } }
        public static string Deployments_TicketPlaceholder { get { return ResourceManager.GetString("Deployments.TicketPlaceholder", resourceCulture); } }
        public static string Deployments_DescriptionPlaceholder { get { return ResourceManager.GetString("Deployments.DescriptionPlaceholder", resourceCulture); } }
        public static string Deployments_LastSave { get { return ResourceManager.GetString("Deployments.LastSave", resourceCulture); } }
        public static string Deployments_DataModelsInDeployment { get { return ResourceManager.GetString("Deployments.DataModelsInDeployment", resourceCulture); } }
        public static string Deployments_NoDataModels { get { return ResourceManager.GetString("Deployments.NoDataModels", resourceCulture); } }
        public static string Deployments_SelectDataModel { get { return ResourceManager.GetString("Deployments.SelectDataModel", resourceCulture); } }
        public static string Deployments_SearchModel { get { return ResourceManager.GetString("Deployments.SearchModel", resourceCulture); } }
        public static string Deployments_ChangesSummaryTitle { get { return ResourceManager.GetString("Deployments.ChangesSummaryTitle", resourceCulture); } }
        public static string Deployments_LoadChangesSummary { get { return ResourceManager.GetString("Deployments.LoadChangesSummary", resourceCulture); } }
        public static string Deployments_UploadToAvaPlace { get { return ResourceManager.GetString("Deployments.UploadToAvaPlace", resourceCulture); } }
        public static string Deployments_Uploading { get { return ResourceManager.GetString("Deployments.Uploading", resourceCulture); } }
        public static string Deployments_ExportDataModels { get { return ResourceManager.GetString("Deployments.ExportDataModels", resourceCulture); } }
        public static string Deployments_StatusSameLabel { get { return ResourceManager.GetString("Deployments.StatusSameLabel", resourceCulture); } }
        public static string Deployments_StatusDifferentLabel { get { return ResourceManager.GetString("Deployments.StatusDifferentLabel", resourceCulture); } }
        public static string Deployments_StatusOnlyDbLabel { get { return ResourceManager.GetString("Deployments.StatusOnlyDbLabel", resourceCulture); } }
        public static string Deployments_StatusOnlyAvaLabel { get { return ResourceManager.GetString("Deployments.StatusOnlyAvaLabel", resourceCulture); } }
        public static string Deployments_StatusSame { get { return ResourceManager.GetString("Deployments.StatusSame", resourceCulture); } }
        public static string Deployments_StatusDifferent { get { return ResourceManager.GetString("Deployments.StatusDifferent", resourceCulture); } }
        public static string Deployments_StatusOnlyDb { get { return ResourceManager.GetString("Deployments.StatusOnlyDb", resourceCulture); } }
        public static string Deployments_StatusOnlyAvaPlace { get { return ResourceManager.GetString("Deployments.StatusOnlyAvaPlace", resourceCulture); } }
        public static string Deployments_StatusColumn { get { return ResourceManager.GetString("Deployments.StatusColumn", resourceCulture); } }
        public static string Deployments_FieldsDelta { get { return ResourceManager.GetString("Deployments.FieldsDelta", resourceCulture); } }
        public static string Deployments_FieldsDeltaTitle { get { return ResourceManager.GetString("Deployments.FieldsDeltaTitle", resourceCulture); } }
        public static string Deployments_DetailChanges { get { return ResourceManager.GetString("Deployments.DetailChanges", resourceCulture); } }
        public static string Deployments_Saved { get { return ResourceManager.GetString("Deployments.Saved", resourceCulture); } }
        public static string Deployments_Created { get { return ResourceManager.GetString("Deployments.Created", resourceCulture); } }

        public static string DataModelRecords_Title { get { return ResourceManager.GetString("DataModelRecords.Title", resourceCulture); } }
        public static string DataModelRecords_ModelLabel { get { return ResourceManager.GetString("DataModelRecords.ModelLabel", resourceCulture); } }
        public static string DataModelRecords_SelectModel { get { return ResourceManager.GetString("DataModelRecords.SelectModel", resourceCulture); } }
        public static string DataModelRecords_AllModels { get { return ResourceManager.GetString("DataModelRecords.AllModels", resourceCulture); } }
        public static string DataModelRecords_AddRecord { get { return ResourceManager.GetString("DataModelRecords.AddRecord", resourceCulture); } }
        public static string DataModelRecords_AvaPlaceReadOnly { get { return ResourceManager.GetString("DataModelRecords.AvaPlaceReadOnly", resourceCulture); } }
        public static string DataModelRecords_SelectModelForAvaPlace { get { return ResourceManager.GetString("DataModelRecords.SelectModelForAvaPlace", resourceCulture); } }
        public static string DataModelRecords_FieldValues { get { return ResourceManager.GetString("DataModelRecords.FieldValues", resourceCulture); } }
        public static string DataModelRecords_Localized { get { return ResourceManager.GetString("DataModelRecords.Localized", resourceCulture); } }
        public static string DataModelRecords_NewTitle { get { return ResourceManager.GetString("DataModelRecords.NewTitle", resourceCulture); } }
        public static string DataModelRecords_EditTitle { get { return ResourceManager.GetString("DataModelRecords.EditTitle", resourceCulture); } }
        public static string DataModelRecords_RecordFields { get { return ResourceManager.GetString("DataModelRecords.RecordFields", resourceCulture); } }
        public static string DataModelRecords_LoadingSchema { get { return ResourceManager.GetString("DataModelRecords.LoadingSchema", resourceCulture); } }
        public static string DataModelRecords_NoFields { get { return ResourceManager.GetString("DataModelRecords.NoFields", resourceCulture); } }
        public static string DataModelRecords_Saved { get { return ResourceManager.GetString("DataModelRecords.Saved", resourceCulture); } }
        public static string DataModelRecords_Created { get { return ResourceManager.GetString("DataModelRecords.Created", resourceCulture); } }
        public static string DataModelRecords_DeleteConfirm { get { return ResourceManager.GetString("DataModelRecords.DeleteConfirm", resourceCulture); } }
        public static string DataModelRecords_ViewTitle { get { return ResourceManager.GetString("DataModelRecords.ViewTitle", resourceCulture); } }
        public static string DataModelRecords_View { get { return ResourceManager.GetString("DataModelRecords.View", resourceCulture); } }

        public static string Features_Title { get { return ResourceManager.GetString("Features.Title", resourceCulture); } }
        public static string Features_IncludedFeaturesColumn { get { return ResourceManager.GetString("Features.IncludedFeaturesColumn", resourceCulture); } }
        public static string Features_IncludedModelsColumn { get { return ResourceManager.GetString("Features.IncludedModelsColumn", resourceCulture); } }
        public static string Features_IncludedFeatures { get { return ResourceManager.GetString("Features.IncludedFeatures", resourceCulture); } }
        public static string Features_IncludedDataModels { get { return ResourceManager.GetString("Features.IncludedDataModels", resourceCulture); } }
        public static string Features_CodePlaceholder { get { return ResourceManager.GetString("Features.CodePlaceholder", resourceCulture); } }
        public static string Features_NameCzechPlaceholder { get { return ResourceManager.GetString("Features.NameCzechPlaceholder", resourceCulture); } }
        public static string Features_DescriptionCzechPlaceholder { get { return ResourceManager.GetString("Features.DescriptionCzechPlaceholder", resourceCulture); } }
    }
}
