namespace AVAIntegrationModeler.UseCases.DataModels.Import;

/// <summary>
/// Statické mapování kódu DataModelu na kód oblasti odvozené z adresářové struktury AVAPlace.
/// Zdroj: tree.txt — složka = kód oblasti, soubor dm-{Kód}.json = kód modelu.
/// Modely na kořenové úrovni (bez složky, např. MandantOrganization) ve slovníku nejsou.
/// </summary>
public static class DataModelAreaMapping
{
  private static readonly Dictionary<string, string> _map = new(StringComparer.Ordinal)
  {
    // AssetManagement
    ["AccountingDepreciation"]             = "AssetManagement",
    ["AssetCard"]                          = "AssetManagement",
    ["AssetCardLocation"]                  = "AssetManagement",
    ["AssetType"]                          = "AssetManagement",
    ["InternationalAccountingDepreciation"] = "AssetManagement",
    ["LocationCode"]                       = "AssetManagement",
    ["SubsidyAccountingDepreciation"]      = "AssetManagement",
    ["TaxDepreciation"]                    = "AssetManagement",
    ["TaxDepreciationMethod"]              = "AssetManagement",
    ["TaxGroup"]                           = "AssetManagement",
    ["TransactionTranscriptType"]          = "AssetManagement",
    // Bank
    ["AccountingBankStatementHeader"]      = "Bank",
    ["AccountingBankStatementItem"]        = "Bank",
    ["BankFee"]                            = "Bank",
    ["BankFeeType"]                        = "Bank",
    ["BankPaymentTitle"]                   = "Bank",
    ["DomesticPaymentOrderHeader"]         = "Bank",
    ["DomesticPaymentOrderItem"]           = "Bank",
    ["ForeignPaymentOrder"]                = "Bank",
    ["PaymentOrderItemDetail"]             = "Bank",
    ["PaymentOrderType"]                   = "Bank",
    ["PaymentType"]                        = "Bank",
    ["StatementItemDetail"]                = "Bank",
    ["StatementTransactionType"]           = "Bank",
    // BankApp
    ["BankCard"]                           = "BankApp",
    ["BankPayment"]                        = "BankApp",
    ["BankPaymentAck"]                     = "BankApp",
    ["BankStatement"]                      = "BankApp",
    ["BankStatementAck"]                   = "BankApp",
    ["BankStatementReq"]                   = "BankApp",
    ["BankTransaction"]                    = "BankApp",
    // CashRegister
    ["CashReceiptHeader"]                  = "CashRegister",
    ["CashReceiptItem"]                    = "CashRegister",
    ["CashReceiptType"]                    = "CashRegister",
    // Common
    ["Address"]                            = "Common",
    ["AddressType"]                        = "Common",
    ["BankAccount"]                        = "Common",
    ["BankAccountType"]                    = "Common",
    ["BankInstitution"]                    = "Common",
    ["Contact"]                            = "Common",
    ["ContactCategory"]                    = "Common",
    ["ContactType"]                        = "Common",
    ["CountryType"]                        = "Common",
    ["Currency"]                           = "Common",
    ["DurationUnitType"]                   = "Common",
    ["LegalFormType"]                      = "Common",
    ["LocalizedItem"]                      = "Common",
    ["Nationality"]                        = "Common",
    ["Organization"]                       = "Common",
    ["OrganizationRelation"]               = "Common",
    ["OrganizationRelationType"]           = "Common",
    ["OrganizationUnit"]                   = "Common",
    ["OrganizationUnitType"]               = "Common",
    ["ValidityUnitType"]                   = "Common",
    // CRM
    ["Activity"]                           = "CRM",
    ["ActivityCategory"]                   = "CRM",
    ["ActivityStatus"]                     = "CRM",
    ["ActivityType"]                       = "CRM",
    ["CostCenter"]                         = "CRM",
    ["DependencyActivityAndActivity"]      = "CRM",
    ["DependencyActivityAndTask"]          = "CRM",
    ["DependencyTaskAndTask"]              = "CRM",
    ["FulfillmentActivityCategory"]        = "CRM",
    ["FulfillmentActivityType"]            = "CRM",
    ["OfferHeader"]                        = "CRM",
    ["OfferItem"]                          = "CRM",
    ["OfferType"]                          = "CRM",
    ["SolutionCenter"]                     = "CRM",
    ["SolutionProvidingEmployee"]          = "CRM",
    ["SolutionProvidingOrganization"]      = "CRM",
    ["SolutionProvidingPerson"]            = "CRM",
    ["SolutionRole"]                       = "CRM",
    ["Task"]                               = "CRM",
    ["TaskCategory"]                       = "CRM",
    ["TaskFulfillment"]                    = "CRM",
    ["TaskStatus"]                         = "CRM",
    ["TaskType"]                           = "CRM",
    // DocumentManagementSystem
    ["ConfirmedDocument"]                  = "DocumentManagementSystem",
    ["Document"]                           = "DocumentManagementSystem",
    ["DocumentAgenda"]                     = "DocumentManagementSystem",
    ["DocumentApprovalStatus"]             = "DocumentManagementSystem",
    ["DocumentApprovalType"]               = "DocumentManagementSystem",
    ["DocumentRelation"]                   = "DocumentManagementSystem",
    ["DocumentRelationType"]               = "DocumentManagementSystem",
    ["DocumentState"]                      = "DocumentManagementSystem",
    ["DocumentTag"]                        = "DocumentManagementSystem",
    ["DocumentValidationType"]             = "DocumentManagementSystem",
    ["File"]                               = "DocumentManagementSystem",
    ["FinalRecipient"]                     = "DocumentManagementSystem",
    ["Folder"]                             = "DocumentManagementSystem",
    ["Signatory"]                          = "DocumentManagementSystem",
    ["SignatureLevel"]                      = "DocumentManagementSystem",
    ["SignaturePlaceAnchorAlignment"]       = "DocumentManagementSystem",
    ["SignaturePlaceType"]                  = "DocumentManagementSystem",
    ["SignedDocument"]                      = "DocumentManagementSystem",
    ["SigningStatus"]                       = "DocumentManagementSystem",
    // Examples
    ["ExampleAuthor"]                      = "Examples",
    ["ExampleBook"]                        = "Examples",
    ["ExampleGenre"]                       = "Examples",
    // HumanResources
    ["AttendanceType"]                     = "HumanResources",
    ["Candidate"]                          = "HumanResources",
    ["ContractPosition"]                   = "HumanResources",
    ["CostPool"]                           = "HumanResources",
    ["DisabilityPersonCategory"]           = "HumanResources",
    ["EducationLevel"]                     = "HumanResources",
    ["EducationType"]                      = "HumanResources",
    ["EmployeeAttendance"]                 = "HumanResources",
    ["EmployeeDetail"]                     = "HumanResources",
    ["EmployeeEducation"]                  = "HumanResources",
    ["EmployeeForeignNational"]            = "HumanResources",
    ["EmployeePayroll"]                    = "HumanResources",
    ["EmployeePayrollDocument"]            = "HumanResources",
    ["EmployeePosition"]                   = "HumanResources",
    ["EmployeeQualification"]              = "HumanResources",
    ["EmployeeQualificationEducation"]     = "HumanResources",
    ["EmployeeShift"]                      = "HumanResources",
    ["EmployeeStatusType"]                 = "HumanResources",
    ["EmployeeSupplementaryAttribute"]     = "HumanResources",
    ["EmployeeVacation"]                   = "HumanResources",
    ["Employment"]                         = "HumanResources",
    ["EmploymentChange"]                   = "HumanResources",
    ["EmploymentRelationshipVariant"]      = "HumanResources",
    ["EmploymentStatus"]                   = "HumanResources",
    ["EmploymentStatusClassification"]     = "HumanResources",
    ["EmploymentType"]                     = "HumanResources",
    ["HealthInsurance"]                    = "HumanResources",
    ["JobClassificationChange"]            = "HumanResources",
    ["LocalAdministrativeUnit"]            = "HumanResources",
    ["MaritalStatusType"]                  = "HumanResources",
    ["OccupationalClassification"]         = "HumanResources",
    ["OrganizationUnitPosition"]           = "HumanResources",
    ["OrganizationUnitPositionType"]       = "HumanResources",
    ["PayGroupType"]                       = "HumanResources",
    ["PayIntervalType"]                    = "HumanResources",
    ["PayRateChange"]                      = "HumanResources",
    ["PayrollComponent"]                   = "HumanResources",
    ["PayrollComponentUnit"]               = "HumanResources",
    ["PayrollDocumentType"]                = "HumanResources",
    ["PayrollLocality"]                    = "HumanResources",
    ["PensionType"]                        = "HumanResources",
    ["Person"]                             = "HumanResources",
    ["PersonContractInfo"]                 = "HumanResources",
    ["PersonGenderType"]                   = "HumanResources",
    ["PersonRelation"]                     = "HumanResources",
    ["PersonRelationType"]                 = "HumanResources",
    ["PersonType"]                         = "HumanResources",
    ["PlannedPayrollChange"]               = "HumanResources",
    ["PlannedPosition"]                    = "HumanResources",
    ["PositionRelation"]                   = "HumanResources",
    ["PositionRelationType"]               = "HumanResources",
    ["Profession"]                         = "HumanResources",
    ["ProfessionType"]                     = "HumanResources",
    ["Qualification"]                      = "HumanResources",
    ["QualificationRelation"]              = "HumanResources",
    ["QualificationRelationType"]          = "HumanResources",
    ["QualificationType"]                  = "HumanResources",
    ["ReasonForLabourMarketAccess"]        = "HumanResources",
    ["RegionLabourOffice"]                 = "HumanResources",
    ["ShiftDayType"]                       = "HumanResources",
    ["ShiftPattern"]                       = "HumanResources",
    ["ShiftType"]                          = "HumanResources",
    ["TerminationWay"]                     = "HumanResources",
    ["TerritorialIdentificationRegister"]  = "HumanResources",
    ["WageDeduction"]                      = "HumanResources",
    ["WageDeductionType"]                  = "HumanResources",
    ["WorkActivityType"]                   = "HumanResources",
    ["WorkPermitType"]                     = "HumanResources",
    // Invoicing
    ["Accrual"]                            = "Invoicing",
    ["AccrualAmountType"]                  = "Invoicing",
    ["AdvancedPayment"]                    = "Invoicing",
    ["ExchangeRate"]                       = "Invoicing",
    ["InvoiceType"]                        = "Invoicing",
    ["MasterDataCard"]                     = "Invoicing",
    ["Payment"]                            = "Invoicing",
    ["PaymentMethod"]                      = "Invoicing",
    ["ReceivedInvoiceHeader"]              = "Invoicing",
    ["ReceivedInvoiceItem"]                = "Invoicing",
    ["ReceivedInvoicePayment"]             = "Invoicing",
    ["SalesInvoiceHeader"]                 = "Invoicing",
    ["SalesInvoiceItem"]                   = "Invoicing",
    ["SumAmountLineType"]                  = "Invoicing",
    ["SummationAmount"]                    = "Invoicing",
    ["ValidityExchangeRate"]               = "Invoicing",
    ["VATIn"]                              = "Invoicing",
    // IsDoc
    ["Invoice"]                            = "IsDoc",
    ["InvoicePayment"]                     = "IsDoc",
    // JobOrder
    ["JobOrder"]                           = "JobOrder",
    // Peppol
    ["PeppolDocument"]                     = "Peppol",
    ["PeppolDocumentDirectionType"]        = "Peppol",
    ["PeppolDocumentStateType"]            = "Peppol",
    ["PeppolStateType"]                    = "Peppol",
    // Project
    ["ProjectHeader"]                      = "Project",
    ["ProjectItem"]                        = "Project",
    ["ProjectResource"]                    = "Project",
    ["ProjectResourceType"]                = "Project",
    ["ProjectStatus"]                      = "Project",
    ["ProjectStatusType"]                  = "Project",
    // Tests
    ["TestNestedEntity"]                   = "Tests",
    ["TestRootEntity"]                     = "Tests",
    // Vehicle
    ["AlternativePropulsionType"]          = "Vehicle",
    ["Engine"]                             = "Vehicle",
    ["FuelPumping"]                        = "Vehicle",
    ["FuelTank"]                           = "Vehicle",
    ["FuelTankType"]                       = "Vehicle",
    ["FuelType"]                           = "Vehicle",
    ["LogBook"]                            = "Vehicle",
    ["OwnerResolutionType"]                = "Vehicle",
    ["RoadTax"]                            = "Vehicle",
    ["RoadTaxVehicleCode"]                 = "Vehicle",
    ["TravelType"]                         = "Vehicle",
    ["VehicleFinancialData"]               = "Vehicle",
    ["VehicleRegistrationCertificate"]     = "Vehicle",
    ["VehicleRegistry"]                    = "Vehicle",
    ["VehicleType"]                        = "Vehicle",
    // Warehouse
    ["BarCode"]                            = "Warehouse",
    ["BarCodeType"]                        = "Warehouse",
    ["CardCatalog"]                        = "Warehouse",
    ["CardGroup"]                          = "Warehouse",
    ["CardType"]                           = "Warehouse",
    ["CustomsNomenclature"]                = "Warehouse",
    ["DetailedClosure"]                    = "Warehouse",
    ["Discount"]                           = "Warehouse",
    ["DiscountGroup"]                      = "Warehouse",
    ["DiscountStatus"]                     = "Warehouse",
    ["DiscountType"]                       = "Warehouse",
    ["DiscountValueType"]                  = "Warehouse",
    ["ExciseTaxCode"]                      = "Warehouse",
    ["InventoryCommitee"]                  = "Warehouse",
    ["IssuedOrderHeader"]                  = "Warehouse",
    ["IssuedOrderItem"]                    = "Warehouse",
    ["IssueHeader"]                        = "Warehouse",
    ["IssueItem"]                          = "Warehouse",
    ["IssueItemSerialNumber"]              = "Warehouse",
    ["IssueType"]                          = "Warehouse",
    ["MeasurementUnit"]                    = "Warehouse",
    ["MeasurementUnitConversion"]          = "Warehouse",
    ["MeasurementUnitSpecification"]       = "Warehouse",
    ["MeasurementUnitType"]                = "Warehouse",
    ["OrderDoneType"]                      = "Warehouse",
    ["Package"]                            = "Warehouse",
    ["PriceList"]                          = "Warehouse",
    ["PriceListHeader"]                    = "Warehouse",
    ["PriceListItem"]                      = "Warehouse",
    ["PriceListStatus"]                    = "Warehouse",
    ["PriceListType"]                      = "Warehouse",
    ["PriceType"]                          = "Warehouse",
    ["Quality"]                            = "Warehouse",
    ["ReceivedOrderHeader"]                = "Warehouse",
    ["ReceivedOrderItem"]                  = "Warehouse",
    ["ReceivingHeader"]                    = "Warehouse",
    ["ReceivingItem"]                      = "Warehouse",
    ["ReceivingItemSerialNumber"]          = "Warehouse",
    ["ReceivingType"]                      = "Warehouse",
    ["RecyclingFee"]                       = "Warehouse",
    ["ReferenceNumber"]                    = "Warehouse",
    ["RoleInventoryCommittee"]             = "Warehouse",
    ["SerialNumber"]                       = "Warehouse",
    ["SerialNumberType"]                   = "Warehouse",
    ["StockInventoryHeader"]               = "Warehouse",
    ["StockInventoryItem"]                 = "Warehouse",
    ["StockInventoryType"]                 = "Warehouse",
    ["StockLevel"]                         = "Warehouse",
    ["StockMasterCardSet"]                 = "Warehouse",
    ["StockMasterDataCard"]                = "Warehouse",
    ["Supplier"]                           = "Warehouse",
    ["TaxOn"]                              = "Warehouse",
    ["TransportType"]                      = "Warehouse",
    ["UnitRecalculationType"]              = "Warehouse",
    ["Variant"]                            = "Warehouse",
    ["VATDirectionType"]                   = "Warehouse",
    ["VATMasterCardType"]                  = "Warehouse",
    ["VATType"]                            = "Warehouse",
    ["Warehouse"]                          = "Warehouse",
    ["WarehouseClosureDetail"]             = "Warehouse",
    ["WarehouseClosureHeader"]             = "Warehouse",
    ["WarehouseClosureItem"]               = "Warehouse",
    ["WarehouseClosureType"]               = "Warehouse",
    ["WarehouseLocation"]                  = "Warehouse",
    ["Warranty"]                           = "Warehouse",
  };

  /// <summary>
  /// Pokusí se získat kód oblasti pro daný kód DataModelu.
  /// Vrací <see langword="false"/> pro modely bez oblasti (např. MandantOrganization).
  /// </summary>
  public static bool TryGetAreaCode(string dataModelCode, out string areaCode) =>
    _map.TryGetValue(dataModelCode, out areaCode!);
}
