name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish API
        run: |
          dotnet publish .\AVAIntegrationModeler\src\AVAIntegrationModeler.API\AVAIntegrationModeler.API.csproj `
            -c Release `
            -r win-x64 `
            --self-contained false `
            -o .\publish\API

      - name: Publish Web Syncfusion App
        run: |
          dotnet publish .\AVAIntegrationModeler\src\AVAIntegrationModeler.Web.SyncfusionApp\AVAIntegrationModeler.Web.SyncfusionApp.csproj `
            -c Release `
            -r win-x64 `
            --self-contained false `
            -o .\publish\Web.SyncfusionApp

      - name: Create ZIP
        run: |
          Compress-Archive `
            -Path .\publish\* `
            -DestinationPath .\AVAIntegrationModeler-win-x64.zip

      - name: Upload published ZIP
        uses: actions/upload-artifact@v4
        with:
          name: AVAIntegrationModeler-win-x64
          path: .\AVAIntegrationModeler-win-x64.zip
